name: Surveillance Statut ANAH

on:
  # Permet de lancer manuellement ce workflow depuis l'onglet Actions
  workflow_dispatch:
  # Déclenche le script toutes les heures (à la minute 0 de chaque heure)
  schedule:
    - cron: '0 * * * *'

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de ton dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installe les dépendances Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Exécute le script Python
      # Les secrets sont passés en variables d'environnement
      - name: Run ANAH scraper
        env:
          EMAIL_DESTINATAIRE: ${{ secrets.EMAIL_DESTINATAIRE }}
          EMAIL_ENVOYEUR: ${{ secrets.EMAIL_ENVOYEUR }}
          MDP_ENVOYEUR: ${{ secrets.MDP_ENVOYEUR }}
          ANAH_LOGIN: ${{ secrets.ANAH_LOGIN }}
          ANAH_MDP: ${{ secrets.ANAH_MDP }}
        run: python main.py

      # 5. Sauvegarde le fichier de statut pour la prochaine exécution
      # Ceci va "commiter" et "pusher" le fichier anah_status.json mis à jour
      # sur ton dépôt pour qu'il soit disponible la prochaine fois.
      - name: Commit and push status file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add anah_status.json
          # Commit seulement s'il y a des changements
          git diff --staged --quiet || git commit -m "Mise à jour automatique des statuts ANAH"
          git push
